// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmfvX9i8sEwRNw55vMDSQECCvBNHTtMH4',
    appId: '1:710686474092:web:c7a3de14947f8415dfbd49',
    messagingSenderId: '710686474092',
    projectId: 'projekt-mobilne-d98af',
    authDomain: 'projekt-mobilne-d98af.firebaseapp.com',
    storageBucket: 'projekt-mobilne-d98af.appspot.com',
    measurementId: 'G-QVRQME0KB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClCmRjYIhXSjAi4pVbaqwgpmGXbY3bNhM',
    appId: '1:710686474092:android:990548cdf54d38bcdfbd49',
    messagingSenderId: '710686474092',
    projectId: 'projekt-mobilne-d98af',
    storageBucket: 'projekt-mobilne-d98af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi-oZkxgYNp2orQJlFqmiYZFO2chxKWTg',
    appId: '1:710686474092:ios:11f5c88ddb17992adfbd49',
    messagingSenderId: '710686474092',
    projectId: 'projekt-mobilne-d98af',
    storageBucket: 'projekt-mobilne-d98af.appspot.com',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi-oZkxgYNp2orQJlFqmiYZFO2chxKWTg',
    appId: '1:710686474092:ios:11f5c88ddb17992adfbd49',
    messagingSenderId: '710686474092',
    projectId: 'projekt-mobilne-d98af',
    storageBucket: 'projekt-mobilne-d98af.appspot.com',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmfvX9i8sEwRNw55vMDSQECCvBNHTtMH4',
    appId: '1:710686474092:web:1cba302a1ffbb5f1dfbd49',
    messagingSenderId: '710686474092',
    projectId: 'projekt-mobilne-d98af',
    authDomain: 'projekt-mobilne-d98af.firebaseapp.com',
    storageBucket: 'projekt-mobilne-d98af.appspot.com',
    measurementId: 'G-6KYWX7NWF2',
  );
}
